update ci scripts

diff --git a/bin/ci b/bin/ci
--- a/bin/ci
+++ b/bin/ci
@@ -1,42 +1,72 @@
 #!/bin/sh
 # bin/ci
 
+check_port() {
+  local host=${1} && shift
+  local port=${1} && shift
+  local retries=10
+  local wait=5
+
+  until( nc -zv "${host}" "${port}" ); do
+    ((retries--))
+    if [ $retries -lt 0 ]; then
+      echo "Service ${host}:${port} didn't become ready in time."
+      exit 1
+    fi
+    sleep "${wait}"
+  done
+}
+
 rspec() {
-    bin/wait-for-mysql
+    echo "Waiting for database to become available..."
+    check_port ${DB_HOSTNAME:-localhost} ${DB_PORT:-3306}
 
-    bundle exec rails db:setup
+    # echo "Setting RAILS_ENV..."
+    # bin/rails db:environment:set RAILS_ENV=test
 
-    # use $2 so you can execute it similar to the rspec command
-    # ex: bin/ci rspec <file>
-    bundle exec rspec $2
+    echo "Preparing database..."
+    bundle exec rails db:drop db:setup
+
+    echo "Running rspecs..."
+    bundle exec rspec $*
 }
 
 start() {
-    if [ -f tmp/pids/server.pid ]; then
-        rm -f tmp/pids/server.pid
-    fi
+    # exit the script with non-zero status if any command fails
+    set -e
 
-    bundle exec rails s $*
-}
+    # set up logging by redirecting stderr and stdout to a file
+    exec 3>&1 4>&2 >log/ci.log 2>&1
 
-init_db() {
-    bin/wait-for-mysql
+    echo "Migration status"
+    bundle exec rails db:migrate:status
 
-    bundle exec rails db:drop
-    bundle exec rails db:setup
+    echo "Running migrations..."
+    bundle exec rails db:migrate
+
+    # clean up any existing files in ./tmp
+    rm -rf tmp/*
+
+    # restore stderr and stdout, close file descriptors 3 and 4
+    exec 1>&3 2>&4 3>&- 4>&-
+
+    # reverse set -e
+    set +e
+
+    echo "Starting rails server..."
+    bundle exec rails s -b ${1:-0.0.0.0}
 }
 
 case "$1" in
+    rspec)
+        shift
+        rspec $*
+        ;;
     start)
         shift
         start $*
         ;;
-    rspec)
-        rspec
-        ;;
-    init_db)
-        init_db
-        ;;
     *)
-        echo "Usage: bin/ci {start|rspec|init_db}"
+        echo "Usage: bin/ci start [<bind_ip>]"
+        echo "       bin/ci rspec [<spec/path/to/file.rb>]"
 esac
